sudo: required
dist: trusty
addons:
  firefox: 'latest'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "4"
  - "6"
script:
  # TODO(rictic): reenable integration tests by uncommenting this
  # - xvfb-run npm test

  # temporary, just run unit tests
  - npm run build && ./node_modules/.bin/gulp test:unit

