language: node_js
node_js:
  - "4"
  - "6"
sudo: required
before_script:
- npm install -g mocha bower
- bower install
- npm run build
addons:
  firefox: '46.0'
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: false
script:
- mocha
dist: trusty
